#!/bin/sh -ex

enable_and_start_service() {
    if ! systemctl is-enabled xbnet.service >/dev/null; then
        systemctl enable --now xbnet.service
    fi
}

case "$1" in
configure)
    enable_and_start_service
    ;;
esac
