name: build

permissions:
  contents: write

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Build Tools
        run: cargo install cross cargo-deb
      - name: Build
        run: cross build --verbose --release --target=${{ matrix.target }}
      - name: Deb Package
        run: cargo deb --target=${{ matrix.target }} --no-build --no-strip
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: xbnet-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/xbnet
            target/${{ matrix.target }}/debian/*.deb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - name: Dowload Binaries
        uses: actions/download-artifact@v3
      - name: Move Debs
        run: find . -name \*.deb -exec cp {} ./ \;
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*"
